name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

- name: Comprobar Xcode
  run: |
    xcodebuild -version
    xcode-select -p

      - name: Compilar proyecto iOS
        run: |
          xcodebuild \
            -project ThreeOneOSFive.xcodeproj \
            -scheme 3105 \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath build/3105.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            archive

      - name: Crear IPA sin firma
        run: |
          mkdir -p build/Payload
          cp -R build/3105.xcarchive/Products/Applications/3105.app build/Payload/
          cd build
          zip -r Javi-Gamer-GBox.ipa Payload

      - name: Entregar IPA
        uses: actions/upload-artifact@v4
        with:
          name: Javi-Gamer-GBox-IPA
          path: build/Javi-Gamer-GBox.ipa
          
